# Generated by Django 4.1.7 on 2023-03-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование склада: ')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование: ')),
                ('count', models.IntegerField(verbose_name='Количество товара: ')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Цена товара: ')),
                ('imgage', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('life', models.CharField(choices=[('NOT', 'Без срока годности'), ('YES', 'Со сроком годности')], max_length=50)),
                ('shelf_life', models.DateTimeField(blank=True, null=True, verbose_name='Срок годности: ')),
                ('accessibility', models.BooleanField(default=True, verbose_name='Доступно для продажи: ')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.warehouse', verbose_name='Склад: ')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
